### PR TITLE
- add same dispatch event finish, next_step event for android

### PR DESCRIPTION
**Pull request by congnguyen91**
- Hello @pranavchauhan.
This is my pull request on android: Once user presses step => dispatch an event to js & same in onFinish sequence. 
- Now I make this pull request for iOS
+ Add options 'isTapRecognizerForTagretView' for js.

=== People can know when sequence finish on the screen => not show again later
Let's improve this module more completely & easily to use :)

### CODE REVIEW

**Comment by prscX** [comment]
Many Thanks @congnguyen91 for raising PR to keep native library in sync.

I think we should explore a easy way of upgrading native swift libraries. May be we can configure native swift library in `package.json` dependencies using Github url. I am not sure whether it will work or not. I will give a try. Doing this we don't have to manually upgrade native swift libraries.

If it does not work, I will merge the PR.

Thanks
Pranav

**Comment by congnguyen91** [comment]
@prscX  Hey friend :) I also update full property from lib
I supported them fixed missing properties from switf
https://github.com/aromajoin/material-showcase-ios/issues/36

Now I updated in pull request. React native dev can use almost options like lib.
Please check and merge it :)
Cong
- My facebook contact https://www.facebook.com/ntcong91 ( contact me if you have any question )

**Comment by congnguyen91** [comment]
@prscX  We can try use pod materialShowCase from swift lib :) If I have more time :D I will try 👍

**Comment by prscX** [comment]
Many many thanks @congnguyen91 for putting all the effort.

Merged the PR. Today I will test this once and publish the same on NPM, meantime you can use master branch.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @congnguyen91, I have publish latest V0.0.6 with the PR changes [Release: 6](https://github.com/prscX/react-native-material-showcase-ios/releases). Can you please download and verify the same.

Thanks
Pranav

**Comment by congnguyen91** [comment]
Thanks @prscX ,
I'm trying :D

**Pull request merged**
